version: "3.7"

services:
  
  auth-db:
      image: postgres
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - 5433:5433
  app-db:
      image: postgres
      environment:
        POSTGRES_DB: app-db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - 5432:5432
  keycloak:
      build:
        context: ./src/services/authentication
        dockerfile: ./Dockerfile
      # image: quay.io/keycloak/keycloak:latest
      # volumes:
        # - ./src/services/authentication/realms:/opt/quay.io/keycloak/imports
      # command: 
        # - "-b 0.0.0.0 -Dkeycloak.import=/opt/quay.io/keycloak/imports/realm-export.json"
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: auth-db
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8080:8080
      depends_on:
        - auth-db

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:5.5
    restart: always
    environment:
     PGADMIN_DEFAULT_EMAIL: admin
     PGADMIN_DEFAULT_PASSWORD: admin
     PGADMIN_LISTEN_PORT: 80
    ports:
     - "8100:80"
    volumes:
     - pgadmin-data:/var/lib/pgadmin

  # keycloak:

  #   build:
  #     context: ./src/services/authentication
  #     dockerfile: ./src/authntication/Dockerfile
  #   environment:
  #     - KEYCLOACK_USER=root
  #     - KEYCLOACK_PASSWORD=root
  #     - DB_VENDOR=postgres
  #     - DB_ADDR=auth-db
  #     - DB_USER=keycloack
  #     - DB_PASSWORD=keycloack
  #   ports: 
  #     - 8080:8080
  #   depends_on:
  #     - auth-db

  
  api:
    build: 
      context: './src/services/api'
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 5000:5000
    environment: 
        JWT__Authority: 'http://localhost:8080/auth/realms/master'
        JWT__Audience: 'mus-app'

volumes:
 db-data:
 pgadmin-data: