version: "3.7"

services: 

  auth-db:
    image: postgres:13.1
    environment:
      - POSTGRES_USER=keycloack
      - POSTGRES_PASSWORD=keycloack
      - POSTGRES_DB=keycloack
    ports: 
      - 54320:5432
  
  keycloak:
    build:
      context: ./src/services/authentication
      dockerfile: ./Dockerfile
    environment:
      - KEYCLOACK_USER=root
      - KEYCLOACK_PASSWORD=root
      - DB_VENDOR=postgres
      - DB_ADDR=auth-db
      - DB_USER=keycloack
      - DB_PASSWORD=keycloack
    ports: 
      - 8080:8080
    volumes:
      - /tm/auth-data/
    depends_on:
      - auth-db
  
  api: 
    build: 
      context: './'
      dockerfile: Dockerfile
    working_dir: /src/src/services/api
    ports:
      - 5000:5000
    
